name: Selenium Integration Tests

on:
  push:
    branches:
      - "*" # Runs on all branches except master
      - "!master"
  pull_request:
    branches:
      - master

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install ChromeDriver dynamically
        run: |
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+' | head -1)
          echo "Chrome version: $CHROME_VERSION"
          CHROMEDRIVER_VERSION=$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)
          if [ -z "$CHROMEDRIVER_VERSION" ]; then
            echo "Failed to retrieve ChromeDriver version for Chrome $CHROME_VERSION. Exiting."
            exit 1
          fi
          echo "ChromeDriver version: $CHROMEDRIVER_VERSION"
          wget https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/bin/
          chmod +x /usr/bin/chromedriver

      - name: Build Maven Project and Run Tests
        run: |
          mvn clean test