name: Run UI Automation

on:
  # Setup cron job to schedule runs every day at 5:00 PM UTC
  schedule:
    - cron: '*/5 * * * *'  # Adjust this for your desired time
  # Trigger workflow on every push and pull request to the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from your repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Java 17
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      # Step 3: Cache Maven dependencies for faster builds
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      # Step 4: Install Maven dependencies
      - name: Install dependencies
        run: mvn install -Dmaven.test.skip=true

      # Step 5: Run TestNG tests headlessly
      - name: Run UI Tests
        run: mvn test -Dsurefire.suiteXmlFiles=testng.xml